- name: Get /usr/sap Block Devices
  shell: "aws ec2 describe-volumes --region={{ placement.region }} --filters Name=attachment.instance-id,Values={{ instance_id }} Name=tag:filesystem,Values=usr_sap"
  register: volumes_usr_sap
  changed_when: false

- name: Set /usr/sap Block Device Variable
  set_fact:
    ebs_usr_sap: "{{ volumes_usr_sap.stdout }}"

- name: Get /usr/sap Device
  shell: "nvme list | awk '/{{ ebs_usr_sap.Volumes[0].VolumeId | regex_replace(\"-\") }}/ {print $1}'"
  register: device_usr_sap
  changed_when: false
  
- name: Create a /usr/sap as xfs filesystem
  filesystem:
    fstype: xfs
    dev: "{{ device_usr_sap.stdout }}"
    resizefs: no

- name: Create /usr/sap directory
  file:
    path: /usr/sap
    state: directory
    mode: '0755'

- name: Get /usr/sap UUID
  shell: blkid -s UUID -o value "{{ device_usr_sap.stdout }}"
  register: usr_sap_uuid
  changed_when: false

- name: Mount File System
  mount:
    path: "/usr/sap"
    src: "UUID={{ usr_sap_uuid.stdout }}"
    fstype: xfs
    state: mounted