- name: Set Hostname
  hostname:
    name: "{{ tags.hostname }}"

- name: Ensure DHCP does not change hostname
  lineinfile:
    path: /etc/sysconfig/network/dhcp
    regexp: '^DHCLIENT_SET_HOSTNAME='
    line: DHCLIENT_SET_HOSTNAME="no"

- name: Ensure preserve_hostname is set
  lineinfile:
    path: /etc/cloud/cloud.cfg
    regexp: '^preserve_hostname:'
    line: "preserve_hostname: true"
#TODO
- name: Add IP address of all hosts to all hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item].ansible_host }} {{item}}"
    state: present
  when: hostvars[item].ansible_host is defined
  with_items: "{{ groups['tag_sap_sid_' + tags['sap-sid'] ] }}"

- name: Update all Zypper packages
  zypper:
    name: '*'
    state: latest

- name: Apply all Zypper patches
  zypper:
    name: '*'
    state: latest
    type: patch

- name: Install saptune
  zypper:
    name: 'saptune'
    state: latest

- name: Install nfs-utils
  zypper:
    name: 'nfs-utils'
    state: latest

- name: Install nvme-cli
  zypper:
    name: 'nvme-cli'
    state: latest

- name: Download AWS DataProvider
  get_url:
    url: https://s3.amazonaws.com/aws-data-provider/bin/aws-agent_install.sh
    dest: /tmp/aws-agent_install.sh
  register: DataProvider

- name: Change AWS DataProvider permissions
  file:
    path: /tmp/aws-agent_install.sh
    mode: ugo+x
  when: DataProvider.changed

- name: Install AWS DataProvider
  shell: /tmp/aws-agent_install.sh
  when: DataProvider.changed

- include_tasks: swap.yml