- name: Get swap Block Devices
  shell: "aws ec2 describe-volumes --region={{ placement.region }} --filters Name=attachment.instance-id,Values={{ instance_id }} Name=tag:filesystem,Values=swap"
  register: volumes_swap
  changed_when: false

- name: Set swap Block Device Variable
  set_fact:
    ebs_swap: "{{ volumes_swap.stdout }}"

- name: Get swap Device
  shell: "nvme list | awk '/{{ ebs_swap.Volumes[0].VolumeId | regex_replace(\"-\") }}/ {print $1}'"
  register: device_swap
  changed_when: false
  
- name: Create a swap filesystem
  filesystem:
    fstype: swap
    dev: "{{ device_swap.stdout }}"
    resizefs: no

- name: Get Swap UUID
  shell: blkid -s UUID -o value "{{ device_swap.stdout }}"
  register: swap_uuid
  changed_when: false

- name: Add swap to /etc/fstab
  mount:
    path: "swap"
    src: "UUID={{ swap_uuid.stdout }}"
    fstype: swap
    state: present
  notify: "Activate Swap"