plugin: aws_ec2

regions: 
  - eu-central-1

filters:
  tag-key: terraform-module

strict: False
keyed_groups:
  - key: tags
    prefix: tag
  - key: instance_type
    prefix: aws_instance_type
  - key: placement.region
    prefix: aws_region
  - key: tags['sap-sid']
    prefix: sap_sid
hostnames:
  - ip-address
  - dns-name
  - tag:Name
  - private-ip-address
compose:
  ansible_host: private_ip_address