- name: Update netconfig
  command: netconfig update -f


- name: Change AWS DataProvider permissions
  file:
    path: /tmp/aws-agent_install.sh
    mode: ugo+x
  listen: "Install AWS DataProvider"

- name: Run Installation of AWS DataProvider
  command: /tmp/aws-agent_install.sh
  listen: "Install AWS DataProvider"

- name: Activate Swap
  command: swapon -L SWAP
  ignore_errors: yes

- name: Restart chrony service
  service: 
    name: chronyd
    state: restarted
  