- name: Update netconfig
  command: netconfig update -f

- name: Activate Swap
  command: swapon -U "{{ swap_uuid.stdout }}"
  ignore_errors: yes

- name: Restart chrony service
  service: 
    name: chronyd
    state: restarted
  