---
- hosts: all
  strategy: free
  remote_user: ec2-user
  become: true
  become_user: root
  roles:
    - common

- hosts: tag_sap_instance_type_ascs
  strategy: free
  remote_user: ec2-user
  become: true
  become_user: root
  roles:
    - ascs

- hosts: tag_sap_instance_type_appserver
  strategy: free
  remote_user: ec2-user
  become: true
  become_user: root
  roles:
    - appserver

- hosts: tag_sap_instance_type_hdb
  strategy: free
  remote_user: ec2-user
  become: true
  become_user: root
  roles:
    - hana_singlenode